global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
# Prometheus itself
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

# Nginx
- job_name: 'nginx'
  static_configs:
  - targets: [ 'nginx:8080' ]
  metrics_path: '/nginx_status'
  scrape_interval: 30s

# Keycloak
- job_name: 'keycloak'
  static_configs:
  - targets: [ 'keycloak:8080' ]
  metrics_path: '/metrics'
  scrape_interval: 30s

# Redis
- job_name: 'redis'
  static_configs:
  - targets: [ 'redis:6379' ]

# Postgres
- job_name: 'postgres'
  static_configs:
  - targets: [ 'postgres:5432' ]

# Docker daemon (if metrics enabled)
- job_name: 'docker'
  static_configs:
  - targets: [ 'host.docker.internal:9323' ]
  scrape_interval: 30s

# Node exporter (if deployed)
- job_name: 'node'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
