# Traefik dynamic configuration
# Middleware and additional routing rules

http:
  middlewares:
    # Security headers
    secure-headers:
      headers:
        accessControlAllowMethods:
        - GET
        - OPTIONS
        - PUT
        - POST
        - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
        - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    # Rate limiting
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    # IP whitelist for admin services (adjust as needed)
    admin-whitelist:
      ipWhiteList:
        sourceRange:
        - "127.0.0.1/32"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"

    # Redirect HTTP to HTTPS
    redirect-to-https:
      redirectScheme:
        scheme: https

  # Additional routers for special cases
  routers:
    # Redirect HTTP to HTTPS
    http-catchall:
      rule: "hostregexp(`{host:.+}`)"
      entrypoints:
      - "web"
      middlewares:
      - "redirect-to-https"
      service: "noop@internal"
