{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-core.fullname" . }}-redis-auth
  labels:
    {{- include "omni-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  password: {{ include "omni-core.redisPassword" . | b64enc }}
{{- end }}
