version: '3.8'

# Omni Core: Essential services only
# For additional services, use separate Helm charts or compose files

services:
  # Core Omni Service
  omni:
    image: ghcr.io/siderolabs/omni:${OMNI_VERSION:-0.41.0}
    container_name: omni-core
    restart: unless-stopped
    environment:
      - OMNI_ACCOUNT_UUID=${OMNI_ACCOUNT_UUID}
      - OMNI_NAME=${OMNI_NAME:-omni}
      - OMNI_WG_IP=${WG_IP:-10.10.1.100}
      - OMNI_DOMAIN=${DOMAIN_NAME}
      # Authentication configuration
      - OMNI_AUTH_SAML_URL=${SAML_URL:-}
      - OMNI_AUTH_OIDC_CLIENT_ID=${AUTH0_CLIENT_ID:-}
      - OMNI_AUTH_OIDC_DOMAIN=${AUTH0_DOMAIN:-}
    volumes:
      - omni_data:/var/lib/omni
      - ./omni/tls.crt:/etc/ssl/certs/omni/tls.crt:ro
      - ./omni/tls.key:/etc/ssl/certs/omni/tls.key:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:8080:8080"  # Only expose to localhost, nginx will proxy
    networks:
      - omni-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Reverse Proxy and SSL Termination (Essential)
  nginx:
    image: nginx:alpine
    container_name: omni-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"    # Nginx status/admin
      - "8090:8090"    # Omni Machine API
      - "8100:8100"    # Omni K8s Proxy
      - "50180:50180/udp"  # WireGuard
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./omni/tls.crt:/etc/nginx/ssl/tls.crt:ro
      - ./omni/tls.key:/etc/nginx/ssl/tls.key:ro
      - nginx_logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - omni
    networks:
      - omni-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/nginx_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Redis for Session Storage (Essential)
  redis:
    image: redis:7-alpine
    container_name: omni-redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:6379:6379"  # Only expose to localhost
    networks:
      - omni-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  omni-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  omni_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local
